[package]
name = "maturin_build"
version = "0.1.0"
edition = "2021"

[lib]
name = "maturin_build"
crate-type = ["cdylib", "lib"]

[dependencies]
pyo3 = { version = "0.16", features = ["extension-module", "multiple-pymethods"], optional = true }

[features]
python = ["pyo3"]
