[build-system]
requires = ["maturin[patchelf]>=0.13,<0.14"]
build-backend = "maturin"

[project]
name = "maturin_build"
classifiers = [
]
requires-python = ">=3.7"

[tool.maturin]
features = ["python"]
